### ISSUE TITLE
Is REPLICATE_API_TOKEN the URL of the downloaded model, and do I need to change the configuration of REPLICATE_MODEL_ENDPOINT?

### ISSUE THREAD

**Issue by kk990926** [a16z-infra/llama2-chatbot#18]

**Comment by kk990926** [comment]
> 
Thank you for your reply, I went to get the individual API and tried to use the default ENDPOINT but got an error ReplicateError: Invalid model_version: . Expected format: owner/name:version  Do you know how to solve this problem?

**Comment by rajko-rad** [comment]
what was the default endpoint you were using?

You should be able to find all the correct default endpoints in this file:
https://github.com/a16z-infra/llama2-chatbot/blob/main/.env_template

**Comment by kk990926** [comment]
> what was the default endpoint you were using?
> 
> You should be able to find all the correct default endpoints in this file: https://github.com/a16z-infra/llama2-chatbot/blob/main/.env_template

Understood, thanks for the reply, first time using replicate not familiar with it.

**Comment by andresgarcia0313** [comment]
Could you please add the way to obtain the replicate_api_token I did not find the way to obtain it

**Comment by zeke** [comment]
@andresgarcia0313 Replicate is a cloud service for running models, and this app uses Replicate's hosted Llama models for inference.

To get a Replicate API token, go to [replicate.com/account](https://replicate.com/account), log in using your GitHub account, then you'll have an API token you can copy and paste into your local `.env` file. Hope that helps!

I've opened a PR to clarify this in the README here: https://github.com/a16z-infra/llama2-chatbot/pull/23
