### ISSUE TITLE
Could you please add the way to obtain the replicate_api_token I did not find the way to obtain it

### ISSUE THREAD

**Issue by andresgarcia0313** [a16z-infra/llama2-chatbot#21]
Could you please add the way to obtain the replicate_api_token I did not find the way to obtain it

**Comment by bot66** [comment]
https://replicate.com/signin?next=/account/api-tokens

**Comment by rajko-rad** [comment]
thanks for both the question and response!!

**Comment by zeke** [comment]
Opened a PR to make this clear for future contributors: https://github.com/a16z-infra/llama2-chatbot/pull/23
