### ISSUE TITLE
Doesn't work out of the box locally - Auth0 setup & configuration instructions missing

### ISSUE THREAD

**Issue by evangineer** [a16z-infra/llama2-chatbot#25]
Need to setup an account with https://auth0.com, create an application and then setup environment variables for `AUTH0_CLIENTID` and `AUTH0_DOMAIN`.

Also need to correctly configure both Callback and Logout URLs (I believe, don't have it working yet).

**Comment by matt-bornstein** [comment]
Sorry, we should have included this in the installation instructions. This has now been updated. Take a look and let us know if you're able to get it running.

**Comment by evangineer** [comment]
Works for me now, thank you!

The instructions for setting up Auth0 were exactly what I needed.
